import type { IColorsCollection, IPrimitiveColors } from '@theme/types';

export const primitiveColors: IPrimitiveColors = {
  ebonyClay: '#242f42',
  poloBlue: '#8ca7d4',
  shuttleGray: '#63799e',
  white: '#ffffff',
  malibu: '#7ba9ff',
  alto: '#cfcfcf',
  oxfordBlue: '#303a4a',
  greenPea: '#185b3c',
  bullShot: '#8b4a20',
  mirage: '#141c29',
  blueBayoux: '#4c5d7b',
};

export const LightColorsColections: IColorsCollection = {
  backgroundBase: primitiveColors.mirage,
  textLight: primitiveColors.poloBlue,
  textDark: primitiveColors.mirage,
  frameBackground: primitiveColors.blueBayoux,
  textWhite: primitiveColors.white,
  mainFormText: primitiveColors.blueBayoux,
  secondFormText: primitiveColors.alto,
  mainFormField: primitiveColors.oxfordBlue,
  secondaryFormField: primitiveColors.ebonyClay,
  looseFormField: primitiveColors.bullShot,
  winFormField: primitiveColors.greenPea,
  buttonBackground: primitiveColors.ebonyClay,
  frameMainFields: primitiveColors.blueBayoux,
  logo: primitiveColors.poloBlue,
  thirdFormText: primitiveColors.white,
  lightFormField: primitiveColors.poloBlue,
  buttonDisabled: primitiveColors.oxfordBlue,
  buttonDisabledText: primitiveColors.blueBayoux,
};

export const DarkColorsColections: IColorsCollection = {
  backgroundBase: primitiveColors.mirage,
  textDark: primitiveColors.mirage,
  textLight: primitiveColors.poloBlue,
  frameBackground: primitiveColors.blueBayoux,
  textWhite: primitiveColors.white,
  mainFormText: primitiveColors.malibu,
  secondFormText: primitiveColors.alto,
  mainFormField: primitiveColors.oxfordBlue,
  secondaryFormField: primitiveColors.ebonyClay,
  looseFormField: primitiveColors.bullShot,
  winFormField: primitiveColors.greenPea,
  buttonBackground: primitiveColors.ebonyClay,
  frameMainFields: primitiveColors.blueBayoux,
  logo: primitiveColors.poloBlue,
  thirdFormText: primitiveColors.white,
  lightFormField: primitiveColors.poloBlue,
  buttonDisabled: primitiveColors.oxfordBlue,
  buttonDisabledText: primitiveColors.blueBayoux,
};
